# Generated by Django 3.1.1 on 2020-09-18 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_of',
            field=models.ManyToManyField(blank=True, related_name='gallery_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='gallery_photos', to='photogallery.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
