# Generated by Django 3.1.1 on 2020-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0002_auto_20200918_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='media/photos/IMG_1048.jpeg', upload_to='photos/'),
        ),
    ]
