# Generated by Django 3.1.1 on 2020-10-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_auto_20200929_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pinned',
        ),
    ]
